version: "3.9"
services:
  #######
  # Business Partner Issuer
  #######
  bpa-issuer:
    image: mujtabaidrees94/business-partner-agent:0.12.0
    depends_on:
      - bpa-agent-issuer
    environment:
      JAVA_OPTS: >
        -Dbpa.acapy.url=http://bpa-agent-issuer:${ACAPY_ADMIN_PORT}
        -Dbpa.acapy.apiKey=${ACAPY_ADMIN_URL_API_KEY}
        -Dmicronaut.security.enabled=${BPA_SECURITY_ENABLED}
        -Dmicronaut.server.port=${BPA_PORT}
        -Dmicronaut.config.files=${BPA_CONFIG_FILES}
        -Dmicronaut.session.http.cookie-secure=false
        -Dbpa.pg.url=jdbc:postgresql://${POSTGRESQL_HOST}/${POSTGRESQL_USER}
        -Dbpa.pg.username=${POSTGRESQL_USER}
        -Dbpa.pg.password=${POSTGRESQL_PASSWORD}
        -Dbpa.host=${BPA_HOST}
        -Dbpa.scheme=${BPA_SCHEME}
      BPA_WEB_MODE: ${BPA_WEB_MODE}
      BPA_LEDGER_BROWSER: ${BPA_LEDGER_BROWSER}
      BPA_BOOTSTRAP_UN: ${BPA_BOOTSTRAP_UN}
      BPA_BOOTSTRAP_PW: ${BPA_BOOTSTRAP_PW}
      ACAPY_ENDPOINT: ${ACAPY_ENDPOINT}
      AGENT_NAME: ${AGENT_NAME}
      BPA_IMPRINT_URL: ${BPA_IMPRINT_URL}
      BPA_PRIVACY_POLICY_URL: ${BPA_PRIVACY_POLICY_URL}
      BPA_CREDDEF_REVOCATION_REGISTRY_SIZE: ${BPA_CREDDEF_REVOCATION_REGISTRY_SIZE}
      # MAIL_USERNAME: ${MAIL_USERNAME}
      # MAILJET_API_KEY: ${MAILJET_API_KEY}
      # MAILJET_API_SECRET: ${MAILJET_API_SECRET}
    ports:
      - 80:${BPA_PORT}
    restart: always
  bpa-agent-issuer:
    image: bcgovimages/aries-cloudagent:py36-1.16-1_0.8.0
    ports:
      - ${ACAPY_ADMIN_PORT}:${ACAPY_ADMIN_PORT}
      - ${ACAPY_HTTP_PORT}:${ACAPY_HTTP_PORT}
    depends_on:
      - bpa-wallet-db-issuer
    entrypoint: /bin/bash
    command: [
        "-c",
        "sleep 15;
        aca-py start \
        --arg-file acapy-static-args.yml \
        --inbound-transport http '0.0.0.0' ${ACAPY_HTTP_PORT} \
        --endpoint ${ACAPY_ENDPOINT} \
        --wallet-name '${ACAPY_WALLET_DATABASE}' \
        --wallet-key '${ACAPY_WALLET_ENCRYPTION_KEY}' \
        --wallet-storage-type '${ACAPY_WALLET_TYPE}' \
        --wallet-storage-config '{\"url\":\"${POSTGRESQL_HOST}:5432\",\"max_connections\":5}' \
        --wallet-storage-creds '{\"account\":\"${POSTGRESQL_USER}\",\"password\":\"${POSTGRESQL_PASSWORD}\",\"admin_account\":\"${POSTGRESQL_USER}\",\"admin_password\":\"${POSTGRESQL_PASSWORD}\"}' \
        --seed '${ACAPY_SEED}' \
        --admin '0.0.0.0' ${ACAPY_ADMIN_PORT} \
        --label '${AGENT_NAME}' \
        ${ACAPY_ADMIN_CONFIG} \
        ${ACAPY_READ_ONLY_MODE} \
        ${ACAPY_TAILS_BASE_URL} \
        ${ACAPY_TAILS_UPLOAD_URL} \
        "
    ]
    volumes:
      - "./acapy-static-args.yml:/home/indy/acapy-static-args.yml"
      - "./genesis-transaction-list.yml:/home/indy/genesis-transaction-list.yml"
  bpa-wallet-db-issuer:
    image: "postgres:14-alpine"
    environment:
      - POSTGRES_USER=${POSTGRESQL_USER}
      - POSTGRES_PASSWORD=${POSTGRESQL_PASSWORD}
    ports:
      - ${POSTGRESQL1_PORT}:5432
    volumes:
      - bpa-wallet-db-issuer:/var/lib/postgresql/data

#######
# Volumes
#######
volumes:
  bpa-wallet-db-issuer:
